name: Build and Inject Secret

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject Secret into HTML
      run: |
        echo "Injecting secret into HTML"
        sed -i 's|MAPS|${{ secrets.MAP_API }}|' ./index.html

    - name: Display the modified HTML
      run: cat ./index.html

    # Example deployment step (optional)
    - name: Deploy
      run: echo "Deployment step here"
